### ISSUE TITLE
Crushed with gtceu1.2.2

### ISSUE THREAD

**Issue by woetal** [YiRanMushroom/GTCEuAO#15]
GT:leisure
[2024-05-30-6.log](https://github.com/YiRanMushroom/GTCEuAO/files/15495830/2024-05-30-6.log)

**Comment by YiRanMushroom** [comment]
Maybe you should try to update GTM to the newest version but I cannot guarantee it would work cuz it seems like the crash is because of Kubejs scripts, and if you update GTM, it could be incompatible. what I reconmend is to wait GT Leisure to update their scripts, and run your game at that version. I think they have already update that, what you need to do is to install the newest version of that modpack. I am pretty sure it would work because I tested just days ago.

**Comment by YiRanMushroom** [comment]
You should first, update my mod to newest version.
second, update GTM to newest version.
third, replace the kubejs folder to the newest modpack version's

**Comment by woetal** [comment]
> You should first, update my mod to newest version. second, update GTM to newest version. third, replace the kubejs folder to the newest modpack version's

ok i will try up later

**Comment by woetal** [comment]
[2024-05-31-1.log.gz](https://github.com/user-attachments/files/15508527/2024-05-31-1.log.gz)
[2024-05-31-2.log.gz](https://github.com/user-attachments/files/15508528/2024-05-31-2.log.gz)

**Comment by YiRanMushroom** [comment]
Try this:
https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.3.a-build_724

**Comment by YiRanMushroom** [comment]
Maybe this one:
https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.3.a-build_723

**Comment by woetal** [comment]
[Uploading 2024-05-31-7.log.gz…]()

**Comment by YiRanMushroom** [comment]
Close due to no further response
