### ISSUE TITLE
Mods Loading Issue

### ISSUE THREAD

**Issue by woetal** [YiRanMushroom/GTCEuAO#2]
while I update to build 10 from build 9 in my ATM9(GTCEU version:1.20.1-1.0.20.b.jar) the mod loading process remains stagnant, but when updated to GTCEU-1.20.1-1.1.1.a, the mods can load normally, but there has something wrong with the GTCEU's mineral processing(the ore from dimensional mineshaft can not be processed by GTCEU's machine)

**Comment by YiRanMushroom** [comment]
I did rewrote the logic of ore processing recipes. Can you test it without my mod to see if the recipes are correct? If the GTCEU-1.20.1-1.1.1.a cannot load the recipe naturely, try to use the newest version of GTCEu. If the problem persists, please issue this under GTCEu's repository, since I am not responsible to fix GTCEu's bug.

**Comment by YiRanMushroom** [comment]
fixed in 2.2.0
